### ISSUE TITLE
CaSS not compiling from zip

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/CASS#176]
I am using Maven 3.3.9
Java version: 1.8.0_265, vendor: Private Build
Ubuntu 16.04
and the CaSS release 1.2.38 source code zip

running 'mvn clean' leads to no problems, but running 'mvn install' afterwards throws this error:
```
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (default-minify) on project cass: The source file [forge.min.js] does not exist. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (default-minify) on project cass: The source file [forge.min.js] does not exist.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: The source file [forge.min.js] does not exist.
	at com.samaxes.maven.minify.plugin.MinifyMojo.execute(MinifyMojo.java:506)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.io.FileNotFoundException: The source file [forge.min.js] does not exist.
	at com.samaxes.maven.minify.plugin.ProcessFilesTask.addNewSourceFile(ProcessFilesTask.java:281)
	at com.samaxes.maven.minify.plugin.ProcessFilesTask.addNewSourceFile(ProcessFilesTask.java:261)
	at com.samaxes.maven.minify.plugin.ProcessFilesTask.<init>(ProcessFilesTask.java:121)
	at com.samaxes.maven.minify.plugin.ProcessJSFilesTask.<init>(ProcessJSFilesTask.java:75)
	at com.samaxes.maven.minify.plugin.MinifyMojo.createJSTask(MinifyMojo.java:649)
	at com.samaxes.maven.minify.plugin.MinifyMojo.createTasks(MinifyMojo.java:631)
	at com.samaxes.maven.minify.plugin.MinifyMojo.execute(MinifyMojo.java:504)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Searching the zip does return the "missing" file however.
Is there a step I am missing?

**Comment by FlorianTolk** [comment]
Update:
Maven was trying to look into `src/main/forge` and into `src/main/webapp/forge` for this file, and while it did exist somewhere in the project, those folders were never created.

Manually creating them does fix the problem.

**Comment by FlorianTolk** [comment]
Once CaSS is up and running, I get this error
![image](https://user-images.githubusercontent.com/33456535/94304649-e1868980-ff3d-11ea-91b9-024b4d46aa59.png)

I am still using `mvn clean install` (with the forge.min.js files moved), followed by `docker-compose up`

**Comment by FlorianTolk** [comment]
Looks like it was an elasticearch error

running `sudo sysctl -w vm.max_map_count=262144` fixes the second error
