### ISSUE TITLE
JS libraries not installed with nodejs 8.11.x 

### ISSUE THREAD

**Issue by aecostas** [cassproject/CASS#64]
Here you can find the trace of the error. I have also tried with 6.14.x and it works fine. However versions `6.x` are no longer stable (https://github.com/nodejs/Release)

```
npm install
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> contextify@0.1.15 install /home/aestevez/devel/cass-client/node_modules/contextify
> node-gyp rebuild

make: se entra en el directorio '/home/aestevez/devel/cass-client/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/aestevez/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/aestevez/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/aestevez/.node-gyp/8.11.1/include/node/v8.h:3851:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/aestevez/.node-gyp/8.11.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/aestevez/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/aestevez/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/aestevez/.node-gyp/8.11.1/include/node/v8.h:3404:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/aestevez/.node-gyp/8.11.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/aestevez/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/aestevez/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/aestevez/.node-gyp/8.11.1/include/node/v8.h:3404:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/aestevez/.node-gyp/8.11.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/aestevez/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/aestevez/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/aestevez/.node-gyp/8.11.1/include/node/v8.h:3404:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/aestevez/.node-gyp/8.11.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
contextify.target.mk:95: fallo en las instrucciones para el objetivo 'Release/obj.target/contextify/src/contextify.o'
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: se sale del directorio '/home/aestevez/devel/cass-client/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/aestevez/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-119-generic
gyp ERR! command "/home/aestevez/.nvm/versions/node/v8.11.1/bin/node" "/home/aestevez/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aestevez/devel/cass-client/node_modules/contextify
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN CASSSimpleClient@1.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aestevez/.npm/_logs/2018-04-23T07_08_40_923Z-debug.log
```

**Comment by Lomilar** [comment]
Hi @aecostas 

The main error is found here:
>npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the contextify@0.1.15 install script.

Node-gyp is a compiler that builds native code. I've found that running `sudo npm install -g cassproject` tends to make node-gyp happy.

If this isn't possible on your environment, let me know and we can pursue other paths forward.

**Comment by aecostas** [comment]
Hi, @Lomilar , thanks for your reply.
I have tried with `sudo`  and `sudo su`, and it keeps failing. See the log:

```
root@GRAD0140UBUNTU:/home/aestevez/devel/cass-client# rm -rf node_modules/
root@GRAD0140UBUNTU:/home/aestevez/devel/cass-client# npm install
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> contextify@0.1.15 install /home/aestevez/devel/cass-client/node_modules/contextify
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN CASSSimpleClient@1.0.1 No repository field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-24T08_08_42_749Z-debug.log
root@GRAD0140UBUNTU:/home/aestevez/devel/cass-client# npm --version
5.8.0
```
The weird thing is that `node-gyp` does not have enough permissions, even tough `npm install` was executed as root

Moreover, according to https://www.npmjs.com/package/contextify, `contextify` should not be needed on nodejs > 0.12, however, it is still there. Would it be something wrong around it?

**Comment by Lomilar** [comment]
Here's my install path on Ubuntu 16.04.

```bash
apt update
apt install nodejs nodejs-legacy npm
npm install cassproject
```

I'll take a look at upgrading the library, as you mentioned.

**Comment by Lomilar** [comment]
I removed JQuery from being a dependency, rewrote some net code and polyfilled XMLHttpRequest (which just uses the HTTP library).

cassproject@0.3.3 is published.

**Comment by aecostas** [comment]
Thanks @Lomilar! Now it works fine with node 8.11.x
I really appreciate your support. I am start working the project and have some questions regarding how to integrate it with existing systems so I probably open new issues with questions.
